HTTP/1.1 200 OK
date: Sat, 01 Nov 2025 07:21:19 GMT
server: uvicorn
content-length: 103
content-type: application/json
x-correlation-id: c39c1393-e018-40dc-beae-e6eb8f5b7024

{"restaurant_id":1,"name":"Green Garden","cuisine":"Mexican","city":"Pune","rating":4.8,"is_open":true}